#set align(center)

#table(
  columns: (auto, auto, auto, auto, auto),
  inset: 10pt,
  align: horizon,
  [*Name*], [*FOSS*], [*License*], [*Linux*], [*Windows*],
  [*Brave Browser*], [Yes], [MPL-2.0], [Yes], [Yes],
  [*Ventoy*], [Yes], [GPLv3], [Yes], [Yes],
  [*nomacs*], [Yes], [GPLv3], [], [Yes],
  [*Discord*], [No], [Proprietary], [Yes], [Yes],
  [*VSCode*], [Source- Yes \ Binary- No], [Source - MIT license \ Binary- Proprietary], [Yes], [Yes],
  [*typst*], [Yes], [Apache-2.0], [Yes],[],
  [*mpv*], [Yes], [GPLv2+], [Yes], [Yes],
  [*Haruna*], [Yes], [GPLv3+], [Yes], [],
  [*KeePassXC*], [Yes], [GPLv2+/GPLv3+], [Yes], [Yes],
  [*qBittorrent*], [Yes], [Source - GPLv2+ \ Binary- GPLv3+], [Yes], [Yes],
  [*FFmpeg*], [Yes], [GPLv2+/LGPLv2.1+], [Yes], [],
  [*Kitty Terminal*], [Yes], [GPLv3], [Yes], [],
  [*Syncthing*], [Yes], [MPL-2.0], [Yes], [],
  [*Rescuezilla*], [Yes], [GPLv3], [Not Applicable], [Not Applicable],
  [*Strawberry Music Player*], [Yes], [GPLv3], [Yes], [],
  [*Cryptomator*], [Yes], [GPLv3], [Yes], [Yes],
  [*GPU Screen Recorder*], [Yes], [GPLv3], [Yes], [Yes],
  [*Kleopatra* \ (Known as GPG4WIN in Windows)], [Yes], [GPLv2+], [Yes], [Yes],
  [*LocalSend*], [Yes], [Apache-2.0], [Yes], [Yes],
)
